import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import './globals.css'
import styles from './page.module.css'
import Link from 'next/link';
import SwitchLangBtn from '@/Components/client/SwitchLangBtn/SwitchLangBtn';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          Header
        </div>
        <SwitchLangBtn />
        <div>
          <Link href={'/'}>首页</Link>
          <Link href={'/copyfund/be-a-leader'}>Create</Link>
          <Link href={'/copyfund/fundlist'}>fundlist</Link>
        </div>
        <AppRouterCacheProvider>
          <main className={styles.main}>
            {children}
          </main>
        </AppRouterCacheProvider>
        <div>
          Footer
        </div>
      </body>
    </html>
  )
}
