import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import './globals.css'
import styles from './page.module.css'
import Link from 'next/link';
import SwitchLangBtn from '@/Components/client/SwitchLangBtn/SwitchLangBtn';
const inter = Inter({ subsets: ['latin'] })
import { dir } from "i18next";
import i18nConfig from "../i18n/i18nConfig";
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}
export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode,
  params: { locale: string };
}) {
  console.log(locale, "rootLayout");

  return (
    <html lang={locale} dir={dir(locale)} data-theme='winter'>
      <body className={inter.className}>
        <div>
          Header
        </div>
        <SwitchLangBtn locale={locale} />
        <div>
          <Link href={'/' + locale} locale={locale}>首页</Link>
          <Link href={locale + '/copyfund/be-a-leader'}>Create</Link>
          <Link href={locale + '/copyfund/fundlist'} locale={locale}>fundlist</Link>
        </div>
        <AppRouterCacheProvider>
          <main className={styles.main}>
            {children}
          </main>
        </AppRouterCacheProvider>
        <div>
          Footer
        </div>
      </body>
    </html >
  )
}
